inherit_gem:
    bixby: bixby_default.yml

# hyrax-spec.gemspec is correct
Style/FileName:
  Exclude:
    - '*.gemspec'
    - 'Gemfile*'
    - 'Guardfile*'
Metrics/BlockLength:
  Exclude:
    - '*_spec.rb'
    - 'lib/hyrax/spec/**/*'
